spring:
  config.activate.on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    username: fisolution
    url: jdbc:h2:tcp://localhost/~/jsonparse

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl