spring:
  config.activate.on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    username: fisolution
    url: jdbc:h2:tcp://localhost/~/jsonparse #?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
#    hikari:
#      data-source-properties:
#        rewriteBatchedStatements: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
spring:
  config.activate.on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/university?rewriteBatchedStatements=true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    hikari:
#      data-source-properties:
#        rewriteBatchedStatements: true